from enum import Enum


class GameState(Enum):
    CLEAN = 'CLEAN',
    SETUP = 'SETUP',
    SETUP_BOARD_SIZE_BEGIN = 'SETUP_BOARD_SIZE_BEGIN',
    SETUP_BOARD_SIZE_END = 'SETUP_BOARD_SIZE_END',
    SETUP_SOURCE_BEGIN = 'SETUP_SOURCE_BEGIN',
    SETUP_SOURCE_END = 'SETUP_SOURCE_END',
    SETUP_TARGET_BEGIN = 'SETUP_TARGET_BEGIN',
    SETUP_TARGET_END = 'SETUP_TARGET_END',
    SETUP_BLOCKED_BEGIN = 'SETUP_BLOCKED_BEGIN',
    SETUP_BLOCKED_END = 'SETUP_BLOCKED_END',
    START = 'START',
    FINISH = 'FINISH'
    RESET = 'RESET',
